CREATE TABLE users (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE todos (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);